### ISSUE TITLE
Y-axis for discrete data shouldn't show values 

### ISSUE THREAD

**Issue by hgui** [verilylifesciences/medtimeline#25]
Bug with the discrete data graphs showing values when it should be value-less

**Comment by laurendukes** [comment]
Also, I noticed sometimes even non-discrete graphs showed repeated labels, for example, 0, 0, 1, 1, 1 when the values probably should have been something like 0, 0.25, 0.5, 0.75, 1.0. It's worth an axis-by-axis check to make sure all the axes make sense.

Root cause of this bug is d0325891e2ac9f3bc87316ddb7bd690c1219d18f so you might find some clues looking at the diffs there.

Please be sure to add unit tests for this if you can. (It's always particularly good to cover in tests what you've accidentally broken at least once!)
